package characters;

import java.util.ArrayList;
import java.util.List;

import sports.Sport;

public abstract class SharedCharacterBehaviour implements Character {

	protected String name;
	protected List<Sport> sports;

	public SharedCharacterBehaviour() {
		sports = new ArrayList<Sport>();
		setName("");
	}
	
	public SharedCharacterBehaviour(String name) {
		sports = new ArrayList<Sport>();
		setName(name);
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getName() {
		return name;
	}
	

	protected void addSport(Sport sport) {
		sports.add(sport);
	}
	
	// Generated by Eclipse

	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		return result;
	}

	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SharedCharacterBehaviour other = (SharedCharacterBehaviour) obj;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		return true;
	}

}
